import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { postsData, tagsData } from './data/blog'

import { getLink } from './common'

import React, {useState, useEffect} from "react";
import {useTheme} from 'next-themes'

import { DarkModeSwitch } from 'react-toggle-dark-mode';

const Home: NextPage = () => {
  const {theme, setTheme} = useTheme()
  // const [isDarkMode, setIsDarkMode] = useState(() => true)

  const [isDarkMode, setDarkMode] = useState(theme === 'dark');

  // const toggleDarkMode = (checked: boolean) => {
  //   setDarkMode(checked);
  // };

  return (
    <>
    <div className={styles.container+ " dark:bg-indigo-600"}>


      <button
        aria-label="Toggle Dark Mode"
        type="button"
        className="p-3 h-12 w-12 order-2 md:order-3"
        onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
      >
             {/* <DarkModeToggle
      onChange={setIsDarkMode}
      checked={isDarkMode}
      size={80}
    /> */}

<DarkModeSwitch
      style={{ marginBottom: '2rem' }}
      checked={isDarkMode}
      onChange={() => {
        theme === 'dark' ? setDarkMode(false) : setDarkMode(true);
      }}
      size={40}
    />

      </button>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={`${styles.title} dark:text-white`}>
          Welcome to <a href="https://nextjs.org" className='dark:text-green-500'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className="bg-white dark:bg-gray-900 rounded-lg px-6 py-8 ring-1 ring-gray-900/5 shadow-xl">
  <div>
    <span className="inline-flex items-center justify-center p-2 bg-indigo-500 rounded-md shadow-lg">
      <svg className="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true"></svg>
    </span>
  </div>
  <h3 className="text-gray-900 dark:text-white mt-5 text-base font-medium tracking-tight">Writes Upside-Down</h3>
  <p className="text-gray-500 dark:text-gray-400 mt-2 text-sm">
    The Zero Gravity Pen can be used to write in any orientation, including upside-down. It even works in outer space.
  </p>
</div>

        <Link href={getLink(`/blog/page/1`)}>
            <a className="p-3 m-3">Pagination</a>
        </Link>

        <ol className="content-left col-span-6">
          {postsData.map((post) => (
            <li key={`post_${post.Id}`} className='bg-black text-fuchsia-200 m-3 p-3'>
              {/* <Link href={`post/${post.Slug}`} passHref as={`post/${post.Slug}`}> for local dev*/}
              {/* <Link href={`./post/${post.Slug}.html`} passHref as={`./post/${post.Slug}.html`}> for local static, but only works on FF and not Chrome. Same works in gh-pages across browsers though */}

              <Link href={getLink(`/blog/post/${post.Slug}`)}>
                <a>{post.Title}</a>
              </Link>
            </li>
          ))}
        </ol>
        <ol className='align-right col-span-6'>
          {tagsData.map((tag) => (
            <li key={`tag_${tag.Slug}`} className='bg-green-500 align-right m-3 p-3 text-white '>
              {/* <Link href={`post/${post.Slug}`} passHref as={`post/${post.Slug}`}> for local dev*/}
              {/* <Link href={`./post/${post.Slug}.html`} passHref as={`./post/${post.Slug}.html`}> for local static, but only works on FF and not Chrome. Same works in gh-pages across browsers though */}

              <Link href={getLink(`/blog/tag/${tag.Slug}/page/1`)}>
                <a>{tag.Title}</a>
              </Link>
            </li>
          ))}
        </ol>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="./vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    </>
  )
}

export default Home
